### ISSUE TITLE
Used to work, but now never works

### ISSUE THREAD

**Issue by Schreck425** [pmahend1/PrettyXML#113] opened 2023-05-10 17:06 UTC
I really liked this plugin but I haven't been able to get it to work for months.  Settings are set to prettify on save,  but when I hit save nothing happens.  I have tried it on multiple types of XML files.  Nothing ever happens.

Is there a log or something I can find to see what is happening?

**Comment by Schreck425** [comment] 2023-05-10 17:13
Down in the bottom right when I use the shortcut Control K L,  I just see a small window popup and say "Prettify XML: Minimizing..."

File doesn't change at all.

**Comment by pmahend1** [comment] 2023-05-10 17:24
Hello. Thanks for reporting. There are some logs you can see in the log window. They are not exhaustive logs though. Could you please let me know
- What OS are you using?
- Do you have prerequisites installed (C# plugin and Dotnet 6 or above) and you can access them from command line(try dotnet -v)
- Do you have valid XML? Could you please share sample XML you are trying?

I got another issue reported that mentioned Format on Save doesn't work on Linux at times. Haven't found solution to it as it is most have to do with VS Code than plugin itself.

**Comment by Schreck425** [comment] 2023-05-10 17:39
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎8/‎25/‎2021
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

C# 1.25.7

dotnet --version
7.0.203

Current Sample

<?xml version="1.0" encoding="UTF-8"?>
<Sims testerOn="true" safeMode="false">
    
    <sim title="Others"                    enabled="true"
         width="300"
         height="500"


         x="1"
         y="1"
         picName="others.png" />
    <sim title="TEXT"
         enabled="true"
         width="300"                   height="500"
         x="301"
         y="1"
         picName="123.png">
    </sim>
</Sims>

It's weird because it used to work.  Makes me wonder if some other plugin in blocking it.

**Comment by Schreck425** [comment] 2023-05-10 17:39
<?xml version="1.0" encoding="UTF-8"?>
<Sims testerOn="true" safeMode="false">
    
    <sim title="Others"                    enabled="true"
         width="300"
         height="500"


         x="1"
         y="1"
         picName="others.png" />
    <sim title="TEXT"
         enabled="true"
         width="300"                   height="500"
         x="301"
         y="1"
         picName="123.png">
    </sim>
</Sims>

**Comment by Schreck425** [comment] 2023-05-10 17:39
The forum for some reason is not pasting my XML correctly

**Comment by Schreck425** [comment] 2023-05-10 17:40
> <?xml version="1.0" encoding="UTF-8"?>
<Sims testerOn="true" safeMode="false">
    
    <sim title="Others"                    enabled="true"
         width="300"
         height="500"


         x="1"
         y="1"
         picName="others.png" />
    <sim title="TEXT"
         enabled="true"
         width="300"                   height="500"
         x="301"
         y="1"
         picName="123.png">
    </sim>
</Sims>

**Comment by pmahend1** [comment] 2023-05-10 17:44
The code you posted is not valid XML. So it wont work. It doesnt have valid start tag.

If you try with only this , it should work

```xml
<sim title="TEXT"
     enabled="true"
     width="300"                   height="500"
     x="301"
     y="1"
     picName="123.png">
</sim>
```

```xml
<?xml version="1.0" encoding="utf-8"?><sim title="TEXT" enabled="true" width="300" height="500" x="301" y="1" picName="123.png"></sim>
```

**Comment by Schreck425** [comment] 2023-05-10 17:49
![testXML](https://github.com/pmahend1/PrettyXML/assets/118386038/e12b40b7-373e-4650-b9b0-e921dd223de4)

**Comment by Schreck425** [comment] 2023-05-10 17:49
Sorry,  my computer crashed you responded before I could paste this.  My browsers read the XML fine.  The indenting right now is exaggerated to see if it gets pretty.

**Comment by pmahend1** [comment] 2023-05-10 17:57
Okay. Could you please confirm whether you have installed [muhammad-sammy/csharp](https://open-vsx.org/extension/muhammad-sammy/csharp) or [Microsoft C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) extension?

**Comment by Schreck425** [comment] 2023-05-10 17:58
You mean C# 1.25.7?  That's what I have on there.

**Comment by pmahend1** [comment] 2023-05-10 18:04
As mentioned above maybe other extension is probably causing issue I think. May be try by right clicking and selecting Pretty XML or open command palette and choose Minimize or Format option and see if it works.

**Comment by Schreck425** [comment] 2023-05-10 18:10
That's one thing I didn't understand on the info page.  What/Where am I right clicking?

**Comment by pmahend1** [comment] 2023-05-10 18:13
You have to right click on Current Active Editor

**Comment by Schreck425** [comment] 2023-05-10 18:13
Ok I see it in your info page,  problem is though I don't have any of those options when I right click

**Comment by Schreck425** [comment] 2023-05-10 18:14
![NoOptions](https://github.com/pmahend1/PrettyXML/assets/118386038/de5d8049-16b1-40ee-9738-f0ba76cce7ab)

**Comment by Schreck425** [comment] 2023-05-10 18:16
Ok caught one thing,  for some reason my editor thinks it's C#,  so I changed it to XML.  Now I get those options.  It now say "Formatting" but still nothing happens...  Might be making progress here

**Comment by Schreck425** [comment] 2023-05-10 18:20
Format and Minimize in command pallet don't really do anything.

**Comment by Schreck425** [comment] 2023-05-10 18:56
It's definitely set to XML now,  not sure why I have to manually change it and it doesn't detect it.  Either way,  I see the options now but they still do nothing unfortunately.

**Comment by pmahend1** [comment] 2023-05-10 20:29
I am unable to reproduce the issue. May be try disabling other extensions except C# , then try if it solves your issue.

**Comment by rt-src** [comment] 2023-05-15 14:02
Hello, yes I have a similar problem, the process hangs and nothing happens.

![1](https://github.com/pmahend1/PrettyXML/assets/48678189/96d3e701-67cf-4eca-abb9-a7df334da3a1)

**Comment by Schreck425** [comment] 2023-05-15 14:04
I've turned off all of the extensions I can in VS code but still no luck.

**Comment by pmahend1** [comment] 2023-05-15 15:34
Okay. Could you try the following
- Check if you have node installed on your machine `node --version`
- Disable all other extensions except C# and PrettyXML
- On Windows, if you are on User version of VS Code, then try System version of VS Code: [System vs User installer](https://code.visualstudio.com/download)
- Try to open vscode from admin command prompt and retry 
     - Open admin powershell/command prompt
     - type `vscode . -n`
     - try formatting

**Comment by Schreck425** [comment] 2023-05-15 15:39
user@XXXX64 ~/Documents/Visual Studio 2019/Projects/Kit/
$ node --version
bash: node: command not found

What is this node command?

**Comment by pmahend1** [comment] 2023-05-15 15:41
@Schreck425 It is [NodeJS](https://nodejs.org/en) 
Please install and see if it solves.

**Comment by rt-src** [comment] 2023-05-15 15:51
@pmahend1 

Not working

1. node version v18.15.0
2. all plugins disabled but C# and PrettyXML
3. installed System version of VS Code
4. open vscode from admin command prompt

![1](https://github.com/pmahend1/PrettyXML/assets/48678189/9acdfd59-8462-4a63-a201-3dc5d062f494)

**Comment by Schreck425** [comment] 2023-05-15 16:03
$ node --version
v18.16.0

Tried other things.  No luck

**Comment by Schreck425** [comment] 2023-05-15 16:05
$ dotnet --version
7.0.203

**Comment by rt-src** [comment] 2023-05-15 16:14
> > @pmahend1
> > Not working
> > ```
> > 1. node version v18.15.0
> > 
> > 2. all plugins disabled but C# and PrettyXML
> > 
> > 3. installed System version of VS Code
> > 
> > 4. open vscode from admin command prompt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![1](https://user-images.githubusercontent.com/48678189/238402918-9acdfd59-8462-4a63-a201-3dc5d062f494.png)
> 
> Could you also check `dotnet --version`? Can you share a sample XML that is not working? I am guessing the XML you are trying may not be a valid XML.

 dotnet version 7.0.203

xml:

`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
	<url><loc>https://site.com/</loc><lastmod>2023-05-10</lastmod><changefreq>monthly</changefreq><priority>0.9</priority>
	</url>
</urlset>`

**Comment by pmahend1** [comment] 2023-05-15 16:18
@rt-src I am unable to reproduce this. I will probably add a setting to plugin to generate logs so that we can get some info on the issue.

**Comment by pmahend1** [comment] 2023-05-19 03:38
I have logs as settings. Please go to VS Code > Settings > Extensions > PrettyXML Settings and turn on Enable Logs.
Try to reproduce the issue. Please report logs here.
Once done you can turn off the setting.

I am hopeful to get more insight on this issue.

![image](https://github.com/pmahend1/PrettyXML/assets/21352870/d30b1a15-a93c-4fe2-803e-ba67a5fe6bb9)

**Comment by rt-src** [comment] 2023-05-19 06:24
@pmahend1 Hi, logs:

[ INFO - 09:23:37] formatXml start
[ WARNING - 09:23:37] docText is null. Fetching from DocumentHelper
[ INFO - 09:23:37] formatWithCommandLine start
[ INFO - 09:23:37] converted input to json {"xmlString":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"><url><loc>https://site.com/</loc><lastmod>2023-05-10</lastmod><changefreq>monthly</changefreq><priority>0.9</priority></url><url><loc>https://site.com/</loc><lastmod>2023-05-10</lastmod><changefreq>monthly</changefreq><priority>0.8</priority></url></urlset>\r\n","actionKind":"Format","formattingOptions":{"IndentLength":4,"UseSingleQuotes":false,"UseSelfClosingTags":true,"FormatOnSave":false,"AllowSingleQuoteInAttributeValue":true,"AddSpaceBeforeSelfClosingTag":true,"WrapCommentTextWithSpaces":true,"AllowWhiteSpaceUnicodesInAttributeValues":true,"PositionFirstAttributeOnSameLine":true,"PositionAllAttributesOnFirstLine":false,"EnableLogs":true}}
[ INFO - 09:23:37] Starting dotnet childProcess at c:\Users\esshi\.vscode\extensions\prateekmahendrakar.prettyxml-3.3.0\lib\XmlFormatter.CommandLine.dll 
[ INFO - 09:23:37] replaceDocumentTextWithProgressForCallback start
[ INFO - 09:23:37] replaceDocumentTextWithProgressForCallback end
[ WARNING - 09:23:37] childProcess errored with exitCode 2147516566
[ ERROR - 09:23:37] undefined : undefined

**Comment by Schreck425** [comment] 2023-05-19 14:55
[ INFO - 9:54:59 AM] minimizeXml start
[ INFO - 9:54:59 AM] formatWithCommandLine start
[ INFO - 9:54:59 AM] converted input to json {"xmlString":"<?xml version=\"1.0\" encoding=\"UTF-8\"?> <urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\"> <url><loc>https://site.com/</loc><lastmod>2023-05-10</lastmod><changefreq>monthly</changefreq><priority>0.9</priority> </url> </urlset>-","actionKind":"Minimize","formattingOptions":{"IndentLength":4,"UseSingleQuotes":false,"UseSelfClosingTags":true,"FormatOnSave":true,"AllowSingleQuoteInAttributeValue":true,"AddSpaceBeforeSelfClosingTag":true,"WrapCommentTextWithSpaces":true,"AllowWhiteSpaceUnicodesInAttributeValues":true,"PositionFirstAttributeOnSameLine":true,"PositionAllAttributesOnFirstLine":true,"EnableLogs":true}}
[ INFO - 9:54:59 AM] Starting dotnet childProcess at c:\Users\e210669\.vscode\extensions\prateekmahendrakar.prettyxml-3.3.0\lib\XmlFormatter.CommandLine.dll 
[ INFO - 9:54:59 AM] replaceDocumentTextWithProgressForCallback start
[ INFO - 9:54:59 AM] replaceDocumentTextWithProgressForCallback end
[ WARNING - 9:54:59 AM] childProcess errored with exitCode 2147516566
[ ERROR - 9:54:59 AM] undefined : undefined

**Comment by pmahend1** [comment] 2023-05-19 15:48
The error is at `childProcess errored with exitCode 2147516566` so `dotnet` command is failing to run on your machine. On further searching for `exitCode 2147516566` it looks like it may have to do with
- dotnet SDK/runtime being corrupted
- Windows update
- Antivirus blocking dotnet command.
- or something else

I would try to do the following
- uninstall/reinstall dotnet SDK
- Install Visual Studio IDE if it is not present
- Check antivirus reports if it has blocked anything
- Try if you could run dotnet executable from command prompt. Raise issue with DotNet github if you can't.

I dont think there is anything I can do right now to fix it from within extension files.

Some references:
- https://gavinmckay.wordpress.com/2018/06/24/fixing-the-program-5656-dotnet-exe-has-exited-with-code-2147450730-0x80008096/
- https://github.com/dotnet/sdk/issues/22629
- https://www.reddit.com/r/VisualStudio/comments/doiniq/program_dotnetexe_has_exited_with_code_2147450751/
- https://stackoverflow.com/questions/48672371/the-program-3984-dotnet-exe-has-exited-with-code-2147450751-0x80008081

**Comment by Schreck425** [comment] 2023-05-19 16:12
Thank you for adding that!  Got mine solved with that information.  I had updated to Dotnet SDK 7.   I uninstalled it and went back to 6.0.408-win-x64 and now the plugin works again.

**Comment by rt-src** [comment] 2023-05-22 06:05
Yes thanks, that helped. I rolled back to Dotnet 6.0.408 and the plugin worked.

**Comment by pmahend1** [comment] 2023-05-22 16:21
Thanks for your patience while I had to add logging to the extension. I wondering why it didn't work on .NET 7 for you guys, I have .NET 7 on my machine, technically it should run .NET 6. I am speculating recent direct .NET 7 might be having some issue. I think the one which comes with Visual Studio installation might be more reliable as I have Visual Studio as well, and have not seen such issues.

**Comment by pmahend1** [comment] 2023-07-05 19:21
Closing this since it is resolved per the conversation.

**Closed by pmahend1** 2023-07-05 19:21 UTC
